name: glados-checkin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: 0 16 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        run: |
          sudo apt update && \
          sudo apt install python3
          sudo apt install python3-setuptools

      - name: requirements
        run: |
          pip3 install -r requirements.txt

      - name: Checkin
        run: |
          python3 checkin.py
        env:
          WECHAT_BOT: ${{ secrets.WECHAT_BOT }}
          COOKIE: ${{ secrets.COOKIE }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
